#!/usr/bin/env bash
set -euo pipefail
ELNEMR_RELEASE_AUDIT_RC3_PERMISSIONS_FIX=1
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail() { echo "RELEASE AUDIT FAILED: $*" >&2; exit 1; }
need() { [[ -f "$2" ]] || fail "$2 is missing"; grep -qE -- "$1" "$2" || fail "$2 is missing expected pattern: $1"; }
forbid() { [[ -f "$2" ]] || fail "$2 is missing"; if grep -qE -- "$1" "$2"; then fail "$2 contains forbidden pattern: $1"; fi; }

SCOPE="${1:-full}"
case "$SCOPE" in android|ios|full) ;; *) fail "unknown audit scope: $SCOPE (expected android, ios, or full)";; esac

common_files=(
  pubspec.yaml README.md EL_NEMR_LANGUAGE.md
  scripts/resolved_dependency_audit.py scripts/feature_wiring_audit.py scripts/package_release.sh
)
android_files=(
  .github/workflows/android.yml gradlew gradlew.bat
  android/gradlew android/gradlew.bat android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml scripts/bootstrap_gradle_wrapper.sh
)
ios_files=(
  .github/workflows/ios.yml ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift ios/Runner/MediaProbe.swift
)
full_extra_files=(.env.example .github/workflows/release.yml android/.gitignore)

required_files=("${common_files[@]}")
[[ "$SCOPE" == android || "$SCOPE" == full ]] && required_files+=("${android_files[@]}")
[[ "$SCOPE" == ios || "$SCOPE" == full ]] && required_files+=("${ios_files[@]}")
[[ "$SCOPE" == full ]] && required_files+=("${full_extra_files[@]}")

missing=()
for f in "${required_files[@]}"; do [[ -f "$f" ]] || missing+=("$f"); done
if ((${#missing[@]})); then
  printf 'RELEASE AUDIT FAILED [%s]: missing required files:\n' "$SCOPE" >&2
  printf '  - %s\n' "${missing[@]}" >&2
  exit 1
fi

# Full-repository hygiene checks. These files are intentionally not Android build blockers.
if [[ "$SCOPE" == full ]]; then
  forbid '^/?gradlew$|^/?gradlew\.bat$|^gradle-wrapper\.jar$' android/.gitignore
  need '^!gradlew$' android/.gitignore
  need '^!gradlew\.bat$' android/.gitignore
  need '^!gradle/wrapper/gradle-wrapper\.properties$' android/.gitignore
  need '^!gradle/wrapper/gradle-wrapper\.jar$' android/.gitignore
  need 'NO API key is required' .env.example
  need "FLUTTER_VERSION: '3\.44\.9'" .github/workflows/release.yml
fi

if [[ "$SCOPE" == android || "$SCOPE" == full ]]; then
  need 'gradle-wrapper\.jar' android/gradlew
  need 'gradle-wrapper\.jar' android/gradlew.bat
  need 'android/gradlew' gradlew
  need 'pushd .*android' gradlew.bat
  need 'call gradlew\.bat' gradlew.bat
  need 'cd .*android' gradlew
  need 'exec sh ./gradlew' gradlew
  need 'gradle-9\.1\.0-bin\.zip' android/gradle/wrapper/gradle-wrapper.properties
  need 'distributionSha256Sum=a17ddd85a26b6a7f5ddb71ff8b05fc5104c0202c6e64782429790c933686c806' android/gradle/wrapper/gradle-wrapper.properties
  need 'raw\.githubusercontent\.com/gradle/gradle/v9\.1\.0/gradle/wrapper/gradle-wrapper\.jar' scripts/bootstrap_gradle_wrapper.sh
  need '76805e32c009c0cf0dd5d206bddc9fb22ea42e84db904b764f3047de095493f3' scripts/bootstrap_gradle_wrapper.sh
  need 'Restore verified Gradle Wrapper' .github/workflows/android.yml
  need 'bootstrap_gradle_wrapper\.sh' .github/workflows/android.yml
  need "FLUTTER_VERSION: '3\.44\.9'" .github/workflows/android.yml
fi

if [[ "$SCOPE" == ios || "$SCOPE" == full ]]; then
  need "FLUTTER_VERSION: '3\.44\.9'" .github/workflows/ios.yml
fi

need '^name: el_nemr_language$' pubspec.yaml
need '^version: 0\.9\.1\+6$' pubspec.yaml
need 'permission_handler: 12\.0\.3' pubspec.yaml
need 'google_mlkit_translation: 0\.15\.1' pubspec.yaml
need 'path_provider: 2\.1\.5' pubspec.yaml
# pubspec.lock is intentionally generated by a real Flutter resolver in CI.
# scripts/resolved_dependency_audit.py is the post-pub-get gate.
need 'whisper_kit: 0\.3\.1' pubspec.yaml
forbid 'hasAllFilesAccess|openAllFilesAccessSettings|ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION' lib/services/file_browser.dart

need 'elnemr/audio_extractor' lib/learning/services/audio_extraction_service.dart
need 'Whisper\(' lib/learning/services/transcription_service.dart
need 'OfflineSpeechModelService' lib/learning/services/transcription_service.dart
need 'downloadModel' lib/learning/services/offline_speech_model_service.dart
need 'Offline AI readiness' lib/screens/settings_screen.dart
need 'OfflineAiSetupScreen' lib/screens/settings_screen.dart
need 'language: .*auto' lib/learning/services/transcription_service.dart
forbid 'LEARNING_ASR_ENDPOINT|api\.openai\.com|MultipartRequest' lib/learning/services/transcription_service.dart
need 'OnDeviceTranslator' lib/learning/services/on_device_translation_service.dart

need 'prepareSource' lib/learning/services/audio_extraction_service.dart
need 'httpHeaders' lib/learning/services/audio_extraction_service.dart
need 'allowSelfSigned' lib/learning/services/audio_extraction_service.dart
need 'Directory\.systemTemp\.createTemp' lib/learning/services/audio_extraction_service.dart
need 'await prepared\.dispose\(\)' lib/learning/services/audio_extraction_service.dart
need 'httpHeaders: _current\.httpHeaders' lib/screens/player_screen.dart
need 'allowSelfSigned: _current\.allowSelfSigned' lib/screens/player_screen.dart
forbid 'probeViaTempDownload\(uri\)' lib/screens/tmd_details_screen.dart
forbid 'Dr Mustafa|Mustafa Salah|supportGithub|supportRazorpay|Razorpay' lib/learning/screens/onboarding_screen.dart
forbid 'Dr Mustafa|Mustafa Salah|supportGithub|supportRazorpay|Razorpay' lib/screens/settings_screen.dart
forbid 'Dr Mustafa|Mustafa Salah' lib/widgets/el_nemr_brand.dart
[[ -f test/audio_extraction_staging_test.dart ]] || fail 'missing authenticated-media staging regression test'
need 'loadAutoLearning' lib/services/subtitle_prefs.dart
need 'Generate a timed transcript from video audio locally' lib/screens/settings_screen.dart
need 'Auto Learning Subtitles' lib/screens/local_screen.dart
need 'content://' lib/screens/player_screen.dart
need 'ContentIdentityService' lib/learning/services/content_identity_service.dart
need 'LocalLanguageCoach' lib/learning/widgets/learning_studio_sheet.dart
need 'SpeechAssessment' lib/learning/widgets/learning_studio_sheet.dart

need 'LearningOnboardingScreen' lib/app.dart
need 'onboardingComplete' lib/learning/services/learner_profile_store.dart
need 'What is your main language\?' lib/learning/screens/onboarding_screen.dart
need 'What do you want to learn\?' lib/learning/screens/onboarding_screen.dart
need 'Learning subtitles ·' lib/screens/player_screen.dart
need 'Generate from video audio · local' lib/screens/player_screen.dart
need 'LearningMode\.watch' lib/learning/widgets/learning_studio_sheet.dart
need 'LearningMode\.learn' lib/learning/widgets/learning_studio_sheet.dart
need 'LearningMode\.listening' lib/learning/widgets/learning_studio_sheet.dart
need 'LearningMode\.speak' lib/learning/widgets/learning_studio_sheet.dart
need 'LearningMode\.test' lib/learning/widgets/learning_studio_sheet.dart
need 'Immersion Auto' lib/learning/widgets/learning_studio_sheet.dart
need 'Smart Coach' lib/learning/widgets/learning_studio_sheet.dart
need 'smartCoachEnabled' lib/learning/widgets/learning_studio_sheet.dart
need '_smartCoachEnabled' lib/screens/player_screen.dart
need 'VocabularyStore' lib/learning/widgets/learning_studio_sheet.dart
need 'VocabularyGrade' lib/learning/services/vocabulary_store.dart
need 'Estimated \$\{estimatedCefr' lib/learning/widgets/learning_studio_sheet.dart
need 'parseDialogueLine' lib/learning/widgets/learning_studio_sheet.dart
forbid 'LearningMode\.(shadow|rolePlay|smartCoach)' lib/learning/models/learning_models.dart

[[ ! -e lib/services/support_links.dart ]] || fail 'legacy visible support-links source still exists'
forbid 'Made with.*Mangesh|Mangesh Ghodke|github\.com/sponsors/mangesh' lib/screens/settings_screen.dart
need 'No API key required' lib/screens/settings_screen.dart
need 'Optional online services' lib/screens/settings_screen.dart
need 'El-Nemr Language' README.md
need 'Optional online enhancements' README.md
[[ -f scripts/resolved_dependency_audit.py ]] || fail 'resolved dependency audit is missing'
[[ -f scripts/feature_wiring_audit.py ]] || fail 'feature wiring audit is missing'
[[ -f scripts/package_release.sh ]] || fail 'package_release.sh is missing'

if [[ "$SCOPE" == full ]]; then
  forbid '^# Copy this file to `\.env` and fill in your API keys\.$' .env.example
  need 'resolved_dependency_audit\.py' .github/workflows/release.yml
  need 'actions/checkout@v7' .github/workflows/release.yml
  need 'actions/download-artifact@v8' .github/workflows/release.yml
  need 'actions/upload-artifact@v7' .github/workflows/release.yml
  forbid '--dart-define=(TMDB_API_KEY|OPENSUBTITLES_API_KEY|LEARNING_LLM_ENDPOINT)' .github/workflows/release.yml
  need 'ANDROID_KEYSTORE_BASE64' .github/workflows/release.yml
  need 'Require persistent Android signing secrets' .github/workflows/release.yml
  need '\.github/workflows/android\.yml' scripts/package_release.sh
fi

for test_file in test/learning_models_el_nemr_test.dart test/vocabulary_store_test.dart test/learner_profile_store_test.dart test/content_identity_service_test.dart test/speech_assessment_test.dart test/local_language_coach_test.dart test/subtitle_prefs_learning_test.dart; do
  [[ -f "$test_file" ]] || fail "missing $test_file"
done


if [[ "$SCOPE" == android || "$SCOPE" == full ]]; then
  need 'namespace = "com\.elnemr\.language"' android/app/build.gradle.kts
  need 'applicationId = "com\.elnemr\.language"' android/app/build.gradle.kts
  need 'minSdk = 26' android/app/build.gradle.kts
  need 'compileSdk = 36' android/app/build.gradle.kts
  forbid 'signingConfigs\.getByName\("debug"\)' android/app/build.gradle.kts
  forbid 'MANAGE_EXTERNAL_STORAGE' android/app/src/main/AndroidManifest.xml
  forbid 'hasAllFilesAccess|openAllFilesAccessSettings|ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION' android/app/src/main/kotlin/com/elnemr/language/FileBrowser.kt
  need 'ACTION_OPEN_DOCUMENT_TREE' android/app/src/main/kotlin/com/elnemr/language/FileBrowser.kt
  need 'ContentUris.withAppendedId' android/app/src/main/kotlin/com/elnemr/language/MediaScanner.kt
  need 'android:label="El-Nemr Language"' android/app/src/main/AndroidManifest.xml
  need 'elnemr/audio_extractor' android/app/src/main/kotlin/com/elnemr/language/AudioExtractor.kt
  need 'createOnDeviceSpeechRecognizer' android/app/src/main/kotlin/com/elnemr/language/SpeechCoach.kt
  need 'isOnDeviceRecognitionAvailable' android/app/src/main/kotlin/com/elnemr/language/SpeechCoach.kt
  need 'EXTRA_PREFER_OFFLINE' android/app/src/main/kotlin/com/elnemr/language/SpeechCoach.kt
  need 'org.gradle.configuration-cache=false' android/gradle.properties
  need 'HttpRangeMediaDataSource' android/app/src/main/kotlin/com/elnemr/language/MediaProbe.kt
  need 'PlayerCodecs\.httpDataSourceFactory' android/app/src/main/kotlin/com/elnemr/language/MediaProbe.kt
  need 'FtpRangeMediaDataSource' android/app/src/main/kotlin/com/elnemr/language/MediaProbe.kt
  need 'matrix:' .github/workflows/android.yml
  need 'pass: \[1, 2, 3\]' .github/workflows/android.yml
  need 'ndk;\$\{WHISPER_NDK_VERSION\}' .github/workflows/android.yml
  need 'flutter analyze' .github/workflows/android.yml
  need 'flutter test --no-pub' .github/workflows/android.yml
  need 'flutter build apk --release --no-pub' .github/workflows/android.yml
  need 'flutter build appbundle --release --no-pub' .github/workflows/android.yml
  need 'feature_wiring_audit\.py' .github/workflows/android.yml
  need 'resolved_dependency_audit\.py' .github/workflows/android.yml
  need 'actions/checkout@v7' .github/workflows/android.yml
  need 'actions/upload-artifact@v7' .github/workflows/android.yml
fi

if [[ "$SCOPE" == ios || "$SCOPE" == full ]]; then
  need 'PRODUCT_BUNDLE_IDENTIFIER = com\.elnemr\.language' ios/Runner.xcodeproj/project.pbxproj
  need 'FlutterGeneratedPluginSwiftPackage' ios/Runner.xcodeproj/project.pbxproj
  need 'IPHONEOS_DEPLOYMENT_TARGET = 17\.0' ios/Runner.xcodeproj/project.pbxproj
  need 'Run Prepare Flutter Framework Script' ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  need 'xcode_backend\.sh.*prepare' ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  need 'elnemr/audio_extractor' ios/Runner/AppDelegate.swift
  need 'requiresOnDeviceRecognition = true' ios/Runner/AppDelegate.swift
  need 'supportsOnDeviceRecognition' ios/Runner/AppDelegate.swift
  forbid 'AVURLAssetHTTPHeaderFieldsKey' ios/Runner/MediaProbe.swift
  need 'probeCustomSource' ios/Runner/MediaProbe.swift
  need 'WebDAVClient\.shared\.makeByteRangeSource' ios/Runner/MediaProbe.swift
  need 'FtpClient\.makeByteRangeSource' ios/Runner/MediaProbe.swift
  need 'resolved_dependency_audit\.py' .github/workflows/ios.yml
  [[ -f .github/workflows/ios.yml ]] || fail 'missing iOS workflow'
  need 'actions/checkout@v7' .github/workflows/ios.yml
  need 'actions/upload-artifact@v7' .github/workflows/ios.yml
  need 'flutter build ios --release --no-codesign --no-pub' .github/workflows/ios.yml
  forbid '--dart-define=(TMDB_API_KEY|OPENSUBTITLES_API_KEY|LEARNING_LLM_ENDPOINT)' .github/workflows/ios.yml
fi

echo "RELEASE AUDIT PASS [$SCOPE]"
